version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-project
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /usr/share/nginx/html
    volumes:
      - ./:/usr/share/nginx/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySql Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: php_db
      MYSQL_ROOT_PASSWORD: php_db
      MYSQL_USER: user
      MYSQL_PASSWORD: safepass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbapp:/var/lib/mysql
    networks:
      - app-network
  
  #phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=safepass
    restart: always
    tty: true
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbapp:
    driver: local
